2024-03-01T21:41:32.364617845Z   File "/opt/python/3.12.1/lib/python3.12/site-packages/debugpy/server/cli.py", line 430, in main2024-03-01T21:41:32.364648045Z     run()
2024-03-01T21:41:32.364652345Z   File "/opt/python/3.12.1/lib/python3.12/site-packages/debugpy/server/cli.py", line 317, in run_module
2024-03-01T21:41:32.364655845Z     run_module_as_main(options.target, alter_argv=True)
2024-03-01T21:41:32.364659045Z   File "/opt/python/3.12.1/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
2024-03-01T21:41:32.383047219Z     return _run_code(code, main_globals, None,
2024-03-01T21:41:32.383067419Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.383072019Z   File "/opt/python/3.12.1/lib/python3.12/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
2024-03-01T21:41:32.383075520Z     exec(code, run_globals)
2024-03-01T21:41:32.383078520Z   File "/tmp/8dc3a37fd948db6/manage.py", line 27, in <module>
2024-03-01T21:41:32.383082120Z     main()
2024-03-01T21:41:32.383085020Z   File "/tmp/8dc3a37fd948db6/manage.py", line 23, in main
2024-03-01T21:41:32.383088220Z     execute_from_command_line(sys.argv)
2024-03-01T21:41:32.383091220Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
2024-03-01T21:41:32.383094320Z     utility.execute()
2024-03-01T21:41:32.383107120Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
2024-03-01T21:41:32.383110420Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2024-03-01T21:41:32.383113320Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
2024-03-01T21:41:32.383116420Z     self.execute(*args, **cmd_options)
2024-03-01T21:41:32.383136820Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 74, in execute
2024-03-01T21:41:32.383140220Z     super().execute(*args, **options)
2024-03-01T21:41:32.383143320Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
2024-03-01T21:41:32.383162220Z     output = self.handle(*args, **options)
2024-03-01T21:41:32.383165220Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.383168020Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 111, in handle
2024-03-01T21:41:32.383171120Z     self.run(**options)
2024-03-01T21:41:32.383174020Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 120, in run
2024-03-01T21:41:32.383177120Z     self.inner_run(None, **options)
2024-03-01T21:41:32.383180021Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
2024-03-01T21:41:32.383183221Z     self.check(display_num_errors=True)
2024-03-01T21:41:32.383192821Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
2024-03-01T21:41:32.431624978Z     all_issues = checks.run_checks(
2024-03-01T21:41:32.431694979Z                  ^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.431701079Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
2024-03-01T21:41:32.431705479Z     new_errors = check(app_configs=app_configs, databases=databases)
2024-03-01T21:41:32.431710079Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.431714079Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
2024-03-01T21:41:32.431717979Z     return check_resolver(resolver)
2024-03-01T21:41:32.431721479Z            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.431730379Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
2024-03-01T21:41:32.431734479Z     return check_method()
2024-03-01T21:41:32.431737979Z            ^^^^^^^^^^^^^^
2024-03-01T21:41:32.431741479Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
2024-03-01T21:41:32.431745179Z     for pattern in self.url_patterns:
2024-03-01T21:41:32.431765580Z                    ^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.431769480Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
2024-03-01T21:41:32.431773380Z     res = instance.__dict__[self.name] = self.func(instance)
2024-03-01T21:41:32.431776980Z                                          ^^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.431780780Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
2024-03-01T21:41:32.431784680Z     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
2024-03-01T21:41:32.431788580Z                        ^^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.431792280Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
2024-03-01T21:41:32.431796180Z     res = instance.__dict__[self.name] = self.func(instance)
2024-03-01T21:41:32.431799880Z                                          ^^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.431803580Z   File "/tmp/8dc3a37fd948db6/antenv/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
2024-03-01T21:41:32.431807480Z     return import_module(self.urlconf_name)
2024-03-01T21:41:32.431811180Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.431832180Z   File "/opt/python/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-03-01T21:41:32.431835880Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-03-01T21:41:32.431864381Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.431869181Z   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-03-01T21:41:32.431873281Z   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-03-01T21:41:32.432027882Z   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-03-01T21:41:32.432032482Z   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-03-01T21:41:32.432036182Z   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
2024-03-01T21:41:32.432040082Z   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-03-01T21:41:32.432043882Z   File "/tmp/8dc3a37fd948db6/Weasys-Apps/urls.py", line 18, in <module>
2024-03-01T21:41:32.432047882Z     from .views import image_generator_view
2024-03-01T21:41:32.432051482Z   File "/tmp/8dc3a37fd948db6/Weasys-Apps/views.py", line 31, in <module>
2024-03-01T21:41:32.432055282Z     openai.api_key = os.environ["OPENAI_API_KEY"]
2024-03-01T21:41:32.440118959Z                      ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2024-03-01T21:41:32.440135159Z   File "<frozen os>", line 685, in __getitem__
2024-03-01T21:41:32.440140559Z KeyError: 'OPENAI_API_KEY'
2024-03-01T21:41:33.009629940Z Performing system checks...
2024-03-01T21:41:33.009948543Z
2024-03-01T21:41:34.292Z ERROR - Container weasy_0_603d1b14 for site weasy has exited, failing site start
2024-03-01T21:41:34.331Z ERROR - Container weasy_0_603d1b14 didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.
2024-03-01T21:41:34.510Z INFO  - Stopping site weasy because it failed during startup.
0.50s - PyDB.dispose_and_kill_all_pydevd_threads: finished0.00s - The following pydb threads may not have finished correctly: pydevd.Reader0.01s - PyDB.dispose_and_kill_all_pydevd_threads: finished0.01s - PyDB.dispose_and_kill_all_pydevd_threads: finished0.01s - ReaderThread: exit0.00s - pydevd.stoptrace()
I+00008.653: Not logging to "<stderr>" anymore.